language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

# install dependencies before running after_script
before_script:
  - pip install tox

# command to run tests
script:
    - make test
