language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
matrix:
  exclude:

before_script:
  - pip3 install tox==3.20.0 black==20.8b1 coverage==5.3

# command to run tests
script:
  - make test
