language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
env:
  - COV=5.3
matrix:
  exclude:

# command to install dependencies
install: pip install coverage==$COV

# command to run tests
script:
    - python setup.py install
    - sh scripts/update_assets.sh
    - python -m unittest tests
