language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

# install dependencies before running after_script
before_script:
  - pip install tox==3.20.0

# command to run tests
script:
    - make test
